name: Malware Scan

on: workflow_dispatch

jobs:
    malware_security_scan:
      name: Malware Scanner
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v3.2.0
        - name: Scan for malware
          uses: dell/common-github-actions/malware-scanner@main
          with:
            directories: .
            options: -ri
